fix: validate aqua

diff --git a/src/commands/update-checksum.yml b/src/commands/update-checksum.yml
--- a/src/commands/update-checksum.yml
+++ b/src/commands/update-checksum.yml
@@ -66,6 +66,10 @@ steps:
       command: |
         set -euo pipefail
 
+        if ! aqua -v; then
+          echo "[ERROR] aqua is required" >&2
+          exit 1
+        fi
         if ! aqua help info >/dev/null; then
           echo "[ERROR] aqua >= v2.10.0 is required" >&2
           exit 1
